const usCities = [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "Charlotte",
    "Indianapolis",
    "San Francisco",
    "Seattle",
    "Denver",
    "Washington",
    "Boston",
    "El Paso",
    "Nashville",
    "Portland",
    "Las Vegas",
    "Detroit",
    "Oklahoma City",
    "Memphis",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Mesa",
    "Kansas City",
    "Atlanta",
    "Long Beach",
    "Colorado Springs",
    "Raleigh",
    "Miami",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Cleveland",
    "Wichita",
    "Arlington",
    "New Orleans",
    "Bakersfield",
    "Tampa",
    "Honolulu",
    "Anaheim",
    "Aurora",
    "Santa Ana",
    "St. Louis",
    "Riverside",
    "Corpus Christi",
    "Lexington",
    "Stockton",
    "Pittsburgh",
    "Anchorage",
    "Cincinnati",
    "Saint Paul",
    "Greensboro",
    "Toledo",
    "Newark",
    "Plano",
    "Henderson",
    "Lincoln",
    "Orlando",
    "Jersey City",
    "Chula Vista",
    "Buffalo",
    "Fort Wayne",
    "Chandler",
    "St. Petersburg",
    "Laredo",
    "Durham",
    "Irvine",
    "Madison",
    "Norfolk",
    "Lubbock",
    "Gilbert",
    "Winston-Salem",
    "Glendale",
    "Hialeah",
    "Garland",
    "Scottsdale",
    "Irving",
    "Chesapeake",
    "North Las Vegas",
    "Fremont",
    "Baton Rouge",
    "Richmond",
    "Boise",
    "San Bernardino",
    "Spokane",
    "Birmingham",
    "Modesto",
    "Des Moines",
    "Rochester",
    "Tacoma",
    "Fontana",
    "Oxnard",
    "Moreno Valley",
    "Fayetteville",
    "Aurora",
    "Glendale",
    "Yonkers",
    "Huntington Beach",
    "Montgomery",
    "Amarillo",
    "Little Rock",
    "Akron",
    "Shreveport",
    "Augusta",
    "Grand Rapids",
    "Mobile",
    "Salt Lake City",
    "Huntsville",
    "Tallahassee",
    "Grand Prairie",
    "Overland Park",
    "Knoxville",
    "Worcester",
    "Brownsville",
    "Newport News",
    "Santa Clarita",
    "Port St. Lucie",
    "Providence",
    "Fort Lauderdale",
    "Chattanooga",
    "Tempe",
    "Oceanside",
    "Garden Grove",
    "Rancho Cucamonga",
    "Cape Coral",
    "Santa Rosa",
    "Vancouver",
    "Sioux Falls",
    "Peoria",
    "Ontario",
    "Jackson",
    "Elk Grove",
    "Springfield",
    "Pembroke Pines",
    "Salem",
    "Corona",
    "Eugene",
    "McKinney",
    "Fort Collins",
    "Lancaster",
    "Cary",
    "Palmdale",
    "Hayward",
    "Salinas",
    "Frisco",
    "Springfield",
    "Pasadena",
    "Macon",
    "Alexandria",
    "Pomona",
    "Lakewood",
    "Sunnyvale",
    "Escondido",
    "Kansas City",
    "Hollywood",
    "Clarksville",
    "Joliet",
    "Rockford",
    "Torrance",
    "Naperville",
    "Bridgeport",
    "Savannah",
    "Mesquite",
    "Killeen",
    "Syracuse",
    "McAllen",
    "Pasadena",
    "Bellevue",
    "Fullerton",
    "Orange",
    "Dayton",
    "Miramar",
    "Thornton",
    "Murrieta",
    "West Valley City",
    "Olathe",
    "Hampton",
    "Warren",
    "Midland",
    "Waco",
    "Charleston",
    "Columbia",
    "Denton",
    "New Haven",
    "Sterling Heights",
    "Cedar Rapids",
    "Roseville",
    "Visalia",
    "Topeka",
    "Thousand Oaks",
    "Cedar Rapids",
    "Thousand Oaks",
    "Topeka",
    "Athens",
    "Simi Valley",
    "Columbia",
    "Olathe",
    "Murfreesboro",
    "Charleston",
    "Visalia",
    "Waco",
    "Hampton",
    "Sterling Heights",
    "New Haven",
    "Denton",
    "Columbia",
    "Charleston",
    "Midland",
    "Columbia",
    "Hampton",
    "Warren",
    "Miramar",
    "Thornton",
    "Dayton",
    "Orange",
    "Fullerton",
    "Bellevue",
    "Pasadena",
    "McAllen",
    "Syracuse",
    "Killeen",
    "Mesquite",
    "Savannah",
    "Bridgeport",
    "Naperville",
    "Torrance",
    "Rockford",
    "Joliet",
    "Clarksville",
    "Hollywood",
    "Kansas City",
    "Escondido",
    "Sunnyvale",
    "Lakewood",
    "Pomona",
    "Alexandria",
    "Macon",
    "Pasadena",
    "Springfield",
    "Frisco",
    "Salinas",
    "Hayward",
    "Palmdale",
    "Cary",
    "Lancaster",
    "Fort Collins",
    "McKinney",
    "Eugene",
    "Corona",
    "Salem",
    "Pembroke Pines",
    "Springfield",
    "Ontario",
    "Peoria",
    "Sioux Falls",
    "Vancouver",
    "Santa Rosa",
    "Cape Coral",
    "Rancho Cucamonga",
    "Garden Grove",
    "Oceanside",
    "Tempe",
    "Chattanooga",
    "Fort Lauderdale",
    "Providence",
    "Port St. Lucie",
    "Santa Clarita",
    "Newport News",
    "Brownsville",
    "Worcester",
    "Knoxville",
    "Overland Park",
    "Grand Prairie",
    "Tallahassee",
    "Huntsville",
    "Salt Lake City",
    "Mobile",
    "Rochester",
    "Des Moines",
    "Modesto",
    "Birmingham",
    "Spokane",
    "San Bernardino",
    "Boise",
    "Richmond",
    "Baton Rouge",
    "Fremont",
    "North Las Vegas",
    "Chesapeake"
];

export default usCities;
